x = int(input())
y = int(input())
print(str(x)+' + '+str(y)+' = '+str(x+y))
print(str(x)+' - '+str(y)+' = '+str(x-y))
print(str(x)+' * '+str(y)+' = '+str(x*y))
print(str(x)+' / '+str(y)+' = '+str(int(x/y)))