th = float(input())
m = float(input())
eng=  float(input())
sc = float(input())
sp = float(input())
print('THAI = '+str(th))
print('MATH = '+str(m))
print('ENGLISH = '+str(eng))
print('SCIENCE = '+str(sc))
print('SPORT = '+str(sp))
print('---')
print('GPA = '+str((m+th+eng+sc+sp)/5))